version: '3.7'
services:
  api:
    image: benm96/api:latest
    build: ./todoEclipse
    depends_on:
    - mysql
    ports:
    - target: 8181
      published: 8181
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=todo 
  front:
    image: benm96/front:latest
    build: ./todoReact/
    ports:
    - target: 3000
      published: 3000
  nginx:
    image: benm96/nginx:latest
    build: ./nginx
    ports:
    - target: 80
      published: 80
    depends_on:
    - api
    - front
